language: node_js
node_js:
- 'node'
sudo: false
cache:
  directories:
  - 'node_modules'
before_install:
  - npm install -g coveralls
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
  - npm run report:text-lcov | coveralls
